import {
	call,
	getPlayerXUID,
	getPlayerSettings,
	getPlayerActivityHistory,
	getPlayerGameClips,
	getPlayerGameClipsFromActivityHistory,
	getPlayerScreenshots,
	getPlayerScreenshotsFromActivityHistory
} from './core/xboxlive';

//#region typings

export type XBLAuthorization = {
	userHash: string;
	XSTSToken: string;
};

export type MediaThumbnail = {
	uri: string;
	fileSize: 0;
	thumbnailType: 'Small' | 'Large';
};

export type MediaUri = {
	uri: string;
	fileSize: number;
	uriType: 'Download';
	expiration: string;
};

export type GameClipNode = {
	gameClipId: string;
	state: string;
	datePublished: string;
	dateRecorded: string;
	lastModified: string;
	userCaption: string;
	type: 'UserGenerated' | 'AutoGenerated';
	durationInSeconds: number;
	scid: string;
	titleId: number;
	rating: number;
	ratingCount: number;
	views: number;
	titleData: string;
	systemProperties: string;
	savedByUser: boolean;
	achievementId: string;
	greatestMomentId: string | null;
	thumbnails: MediaThumbnail[];
	gameClipUris: MediaUri[];
	xuid: string;
	clipName: string;
	titleName: string;
	gameClipLocale: string;
	clipContentAttributes: string;
	deviceType: string;
	commentCount: number;
	likeCount: number;
	shareCount: number;
	partialViews: number;
};

export type PlayerGameClipsResponse = {
	gameClips: GameClipNode[];
	pagingInfo: {
		continuationToken: string | null;
	};
};

export type ScreenshotNode = {
	screenshotId: string;
	resolutionHeight: number;
	resolutionWidth: number;
	state: string;
	datePublished: string;
	dateTaken: string;
	lastModified: string;
	userCaption: string;
	type: 'UserGenerated' | 'AutoGenerated';
	scid: string;
	titleId: number;
	rating: number;
	ratingCount: number;
	views: number;
	titleData: string;
	systemProperties: string;
	savedByUser: boolean;
	achievementId: string;
	greatestMomentId: string | null;
	thumbnails: MediaThumbnail[];
	screenshotUris: MediaUri[];
	xuid: string;
	screenshotName: string;
	titleName: string;
	screenshotLocale: string;
	screenshotContentAttributes: string;
	deviceType: string;
};

export type PlayerScreenshotsResponse = {
	screenshots: ScreenshotNode[];
	pagingInfo: {
		continuationToken: string | null;
	};
};

export type GetUGCQueryString = {
	maxItems?: number;
	continuationToken?: string;
};

export interface IActivityTypeItems {
	items: 'GameDVR' | 'Screenshot' | 'Achievement' | 'Played';
}

export type GetActivityQueryString = {
	numItems?: number;
	contToken?: string;
	pollingToken?: string;
	activityTypes?: IActivityTypeItems['items'];
	excludeTypes?: IActivityTypeItems['items'];
	contentTypes?: 'Game' | 'App';
	startDate?: string;
};

export type ActivityHistoryResponse<T = any> = {
	numItems: number;
	activityItems: T[];
	pollingToken: string;
	pollingIntervalSeconds: string | null;
	contToken: string;
};

export type ScreenshotsFromActivityHistoryNode = {
	screenshotId: string;
	screenshotThumbnail: string;
	screenshotScid: string;
	screenshotName: string;
	screenshotUri: string;
	viewCount: number;
	gameMediaContentLocators: [
		{
			Expiration: string;
			FileSize: number;
			LocatorType: 'Download';
			Uri: string;
		},
		{
			Expiration: string;
			FileSize: number;
			LocatorType: 'Thumbnail_Small';
			Uri: string;
		},
		{
			Expiration: string;
			FileSize: number;
			LocatorType: 'Thumbnail_Large';
			Uri: string;
		}
	];
	contentImageUri: string;
	contentTitle: string;
	platform: string;
	titleId: string;
	uploadTitleId: string;
	activity: {
		screenshotThumbLarge: null;
		screenshotThumbSmall: null;
		screenshotType: null;
		savedByUser: boolean;
		screenshotScid: string;
		screenshotId: string;
		numShares: number;
		numLikes: number;
		numComments: number;
		ugcCaption: string | null;
		authorType: string;
		activityItemType: 'Screenshot';
		userXuid: string;
		date: string;
		contentType: 'Game';
		titleId: string;
		platform: string;
		sandboxid: string;
		userKey: string | null;
		scid: string;
	};
	userImageUriMd: string;
	userImageUriXs: string;
	description: string;
	date: string;
	hasUgc: boolean;
	activityItemType: 'Screenshot';
	contentType: 'Game';
	shortDescription: string;
	itemText: string;
	itemImage: string;
	shareRoot: string;
	feedItemId: string;
	itemRoot: string;
	hasLiked: boolean;
	authorInfo: {
		name: string;
		secondName: string;
		imageUrl: string;
		authorType: string;
		id: string;
	};
	gamertag: string;
	realName: string;
	displayName: string;
	userImageUri: string;
	userXuid: string;
};

export type GameClipsFromActivityHistoryNode = {
	clipId: string;
	clipThumbnail: string;
	downloadUri: string;
	clipName: string;
	clipCaption: string;
	clipScid: string;
	dateRecorded: string;
	viewCount: number;
	gameMediaContentLocators: [
		{
			Expiration: string;
			FileSize: number;
			LocatorType: 'Download';
			Uri: string;
		},
		{
			Expiration: string;
			FileSize: number;
			LocatorType: 'Thumbnail_Small';
			Uri: string;
		},
		{
			Expiration: string;
			FileSize: number;
			LocatorType: 'Thumbnail_Large';
			Uri: string;
		}
	];
	contentImageUri: string;
	contentTitle: string;
	platform: string;
	titleId: string;
	uploadTitleId: string;
	activity: {
		dateRecorded: string;
		numShares: number;
		numLikes: number;
		numComments: number;
		ugcCaption: string | null;
		authorType: string;
		clipId: string;
		clipName: string | null;
		activityItemType: 'GameDVR';
		clipScid: string;
		userXuid: string;
		clipImage: string | null;
		clipType: string | null;
		clipCaption: string | null;
		savedByUser: boolean;
		date: string;
		sharedSourceUser: number;
		contentType: 'Game';
		titleId: string;
		platform: string;
		sandboxid: string;
		userKey: string | null;
		scid: string;
	};
	userImageUriMd: string;
	userImageUriXs: string;
	description: string;
	date: string;
	hasUgc: boolean;
	activityItemType: 'GameDVR';
	contentType: 'Game';
	shortDescription: string;
	itemText: string;
	itemImage: string;
	shareRoot: string;
	feedItemId: string;
	itemRoot: string;
	hasLiked: boolean;
	authorInfo: {
		name: string;
		secondName: string;
		imageUrl: string;
		authorType: string;
		id: string;
	};
	gamertag: string;
	realName: string;
	displayName: string;
	userImageUri: string;
	userXuid: string;
};

export type PlayerScreenshotsFromActivityHistoryResponse = ActivityHistoryResponse<
	ScreenshotsFromActivityHistoryNode
>;

export type PlayerGameClipsFromActivityHistoryResponse = ActivityHistoryResponse<
	GameClipsFromActivityHistoryNode
>;

export interface ISettingItems {
	items:
		| 'GameDisplayPicRaw'
		| 'Gamerscore'
		| 'Gamertag'
		| 'AccountTier'
		| 'XboxOneRep'
		| 'PreferredColor'
		| 'RealName'
		| 'Bio'
		| 'Location'
		| 'ModernGamertag'
		| 'ModernGamertagSuffix'
		| 'UniqueModernGamertag'
		| 'RealNameOverride'
		| 'TenureLevel'
		| 'Watermarks'
		| 'IsQuarantined';
}

export type Setting = ISettingItems['items'];
export type SettingsNode = Array<{
	id: Setting;
	value: string;
}>;

//#endregion
//#region public methods

export {
	call,
	getPlayerXUID,
	getPlayerSettings,
	getPlayerActivityHistory,
	getPlayerGameClips,
	getPlayerGameClipsFromActivityHistory,
	getPlayerScreenshots,
	getPlayerScreenshotsFromActivityHistory
};

//#endregion
